spring.application.name=instagram
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/instagram
spring.datasource.username=postgres
spring.datasource.password=password

#use the Postgres dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#automatically create/update your tables based on your Java code
spring.jpa.hibernate.ddl-auto=update

#SQL queries in terminal
spring.jpa.show-sql=true

#JWT config
security.jwt.secret=REPLACE_ME_IN_PRODUCTION
security.jwt.expiration=86400000

#Cloudinary
cloudinary.cloud-name=YOUR_CLOUD_NAME
cloudinary.api-key=YOUR_API_KEY
cloudinary.api-secret=YOUR_API_SECRET

# EMAIL CONFIGURATION 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SMS CONFIGURATION
twilio.account.sid=YOUR_TWILIO_SID
twilio.auth.token=YOUR_TWILIO_TOKEN
twilio.phone.number=YOUR_TWILIO_NUMBER