spring.application.name=instagram
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/instagram
spring.datasource.username=postgres
spring.datasource.password=password

#use the Postgres dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#automatically create/update your tables based on your Java code
spring.jpa.hibernate.ddl-auto=update

#SQL queries in terminal
spring.jpa.show-sql=true

#JWT config
security.jwt.secret=this-is-my-super-secret-key-for-instagram-clone-that-is-very-long-maybe-too-long-but-i-dont-care-stfu
security.jwt.expiration=86400000